### ISSUE TITLE
Problem with compiling phoenix app

### ISSUE THREAD

**Issue by titzi** [everydayhero/phoenix_swagger#15]
Hi,

I'm not able to compile my app, but I really tried to follow the instructions in the README. This is my controller code:

```
defmodule Api.UsersController do
  use Api.Web, :controller
  import PhoenixSwagger

  swagger_definitions do
    JsonApi.resource(:User, :Users) do
      description "A user of the system."
      attributes do
        user_updated_at :string, "Last update timestamp UTC", format: "ISO-8601"
        user_created_at :string, "First created timestamp UTC"
        street_address :string, "Street address"
        email :string, "Email", required: true
      end
    end
  end

  swagger_path :index do
    get "/users"
    summary "Get users"
    description "Get all users"
    response 200, "Success", Schema.ref(:Users)
    tag "users"
  end

  def index(conn, _params, account) do
    ...
  end
  ...
```

I also added the swagger_spec block to the router.ex.

When trying to start `mix phoenix.server` I get the following error:
```
== Compilation error on file web/controllers/user_controller.ex ==
** (CompileError) web/controllers/user_controller.ex:16: function swagger_path/2 imported from both Api.Router.Helpers and PhoenixSwagger, call is ambiguous
    (elixir) src/elixir_dispatch.erl:112: :elixir_dispatch.expand_import/6
    (elixir) src/elixir_dispatch.erl:83: :elixir_dispatch.dispatch_import/5
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Do you have an idea what's wrong? I'm lost!

One thing: I used the original phoenix_swagger git before I found this (better) version of it. Don't think this is somehow related to this error.

Thanks in advance,
Alex

**Comment by titzi** [comment]
Elixir 1.3.4
Phoenix 1.2.1
edh_phoenix_swagger 0.1.7

**Comment by yagooar** [comment]
I guess the issue is related to this:

```
function swagger_path/2 imported from both Api.Router.Helpers and PhoenixSwagger, call is ambiguous
```

Could it be, that you are using `import PhoenixSwagger` in more than one places in your code?

**Comment by titzi** [comment]
No, that's what I thought, too. I can't find it anywhere. And when I remove the `import PhoenixSwagger` from the controller it cannot find the spec methods. Strange!

**Comment by mbuhot** [comment]
@titzi You shouldn't need to import anything in your `Router` module, just define a `swagger_spec` function like the example in the README.md (https://github.com/everydayhero/phoenix_swagger#usage)

Does your router explicitly declare a `swagger` route?

That would cause phoenix to generate a helper named `swagger_path`, which would clash with `PhoenixSwagger.swagger_path`.

**Comment by titzi** [comment]
It was the swagger route! Thanks! Closing.
