### ISSUE TITLE
Add example object to response

### ISSUE THREAD

**Issue by titzi** [everydayhero/phoenix_swagger#21]
Hi!

is it possible to add example response objects (http://swagger.io/specification/#exampleObject) to the `response` function in `swagger_path`? Like:

`
response 200, "Success", Schema.ref(:User), EXAMPLE_OBJECT
`

that produces something like:

`
{
  "description": "Success",
  "schema": { "$ref": "#/definitions/User" }
  "examples": {
    "application/json": {
      "id": 1,
      ...
    }
}
`

I checked the source but assume it is not supported yet, right?.

Thanks!
Alex

**Comment by mbuhot** [comment]
Looks like there's a field declared for examples in the Response struct but no way to populate it through the DSL, sorry!

According to the spec (http://swagger.io/specification/#responseObject) a response can contain `description`, `schema`, `headers` and `examples`.

How about we add support for `headers` and `examples` as optional keyword args?

```

**Comment by titzi** [comment]
Yes, that would be great!

In my opinion multiple examples would be the right thing because you probably have more than one use case that you want to explain, right? The short version with a single example looks handy, though.

**Comment by mbuhot** [comment]
> because you probably have more than one use case that you want to explain, right 

Yes, unfortunately the swagger spec only allows for one example per mime type (https://github.com/OAI/OpenAPI-Specification/issues/245).

We work around this by merging our swagger spec with additional examples recorded during testing using the [Bureaucrat](https://github.com/api-hogs/bureaucrat) library with the [SwaggerSlateMarkdownWriter](https://github.com/api-hogs/bureaucrat/blob/master/lib/bureaucrat/swagger_slate_markdown_writer.ex) backend.

**Comment by titzi** [comment]
If Swagger spec only allows one example, then this should be the way to go right? Thanks so much!

**Comment by titzi** [comment]
I tried out the Bureaucrat library and your SwaggerSlateMarkdownWriter. I got it working, very cool! It is a great idea to integrate test data into Swagger. I am using ReDoc as the Swagger Spec UI and now I'm thinking about how to benefit from that I idea.
