### ISSUE TITLE
Support single attribute example in JsonApi Resource

### ISSUE THREAD

**Issue by titzi** [everydayhero/phoenix_swagger#24]
A similar request to the one I added before (sorry, I don't want to be a pain in the ass).

I am already able to add example to a `parameter` in `swagger_path` and with the latest change you added I am also able to add a whole example object per response - that's great!

What I would also like to do is add an example to an attribute in a JsonApi Resource, like that:

```elixir
swagger_definitions do
    JsonApi.resource(:User, :Users) do
      description "A user."
      attributes do
        first_name :string, "First Name", example: "John"
        active :boolean, "Active?"
      end
    end
  end
```

or for a single attribute:
```elixir
JsonApi.resource(:Account) do
    description "Update Properties"
    attribute(:company_name, :string, "Company Name", example: "Awesome Inc.")
end
```

returning something like this:

```json
...
"UserResource": {
  ...
  "attributes": {
    "type": "object",
    "properties": {
      "first_name": {
        "type": "string",
        "description": "First Name",
        "example": "John"
      },
      "active": {
        "type": "boolean",
        "description": "Active?"
      }
    }
  }
}
...
```

What do you think?

Alex

**Comment by mbuhot** [comment]
Unfortunately there's no official spec for examples in swagger 2.0 :(
SwaggerUI has some support for examples, and your suggestion looks similar to this issue: https://github.com/swagger-api/swagger-ui/issues/2199#issuecomment-236605347.

Does SwaggerUI (or ReDoc) make use of the examples in the schema like that?
Technically fields that aren't in the swagger spec should have a`x-` prefix.
But if the commonly used tools support such examples then we can add support for it in PhoenixSwagger too 👍

**Comment by titzi** [comment]
Yes, both UI's are supporting it. If it is not in the Spec, I get it :(

Anyway, support for vendor extensions would be great! http://swagger.io/specification/#vendorExtensions

Having that I think I am able to do everything I need. What do you think?

**Comment by titzi** [comment]
For example ReDoc has this: https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-code-samples

This allows adding code examples to your Spec and display it in the UI

**Comment by mbuhot** [comment]
https://github.com/everydayhero/phoenix_swagger/ has merged with https://github.com/xerions/phoenix_swagger.

Support for schema examples has been added in https://github.com/xerions/phoenix_swagger/pull/66 and should work with the JSON-API DSL just as you suggested.

I'll close this issue for now, if you have any issues migrating to https://github.com/xerions/phoenix_swagger please open an issue on that repo and I'll help out.
